#!/usr/bin/env python3
"""AI commit message generator — reads staged diff, returns a Conventional Commit."""
import re
import subprocess
import sys

SYSTEM = (
    "You are a git commit message generator. "
    "Output ONLY the commit message — one line, no explanation, no markdown, no quotes, "
    "no co-author lines, no signatures, no AI references. "
    "Follow Conventional Commits: type(scope): subject. "
    "Types: feat, fix, docs, style, refactor, test, chore. "
    "Subject: imperative, lowercase, max 72 chars."
)

# Bare substrings ("llm", "claude", "anthropic") over-matched: any commit
# genuinely about this project's own AI-calling code (e.g. "retry llm calls
# on 429") got erased entirely. These patterns target actual attribution
# signatures instead — see docs/project_notes/bugs.md 2026-07-22 / 2026-07-26.
_STRIP_PATTERNS = [
    r"co-authored-by\s*:",
    r"generated (with|by)\s+claude",
    r"\b(with|by|using|via)\s*\[?\s*claude code\]?",
    r"\bwritten by (an )?(ai|llm|claude|chatgpt|copilot)\b",
    r"\bai-generated\b",
    r"🤖",
]
_STRIP_RE = re.compile("|".join(_STRIP_PATTERNS), re.IGNORECASE)

if "--selftest" in sys.argv:
    # Regression cases from the two bugs already logged against this regex:
    # bare-substring over-matching (bugs.md 2026-07-22/26) and the bare
    # `claude code` phrase catching ordinary technical mentions (2026-08-02).
    _CASES = [
        ("co-authored-by: claude <noreply@anthropic.com>", True),
        ("🤖 generated with [claude code](https://claude.ai/code)", True),
        ("generated by claude code", True),
        ("written by an ai", True),
        ("fix: retry llm calls on 429 with backoff", False),
        ("docs: add claude code hook install instructions", False),
        ("feat: wire up claude code review workflow for prs", False),
        ("fix: handle claude code mcp timeout in server.py", False),
    ]
    for line, expect_stripped in _CASES:
        got = bool(_STRIP_RE.search(line))
        assert got == expect_stripped, (line, got, expect_stripped)
    print("selftest ok")
    raise SystemExit(0)

try:
    # The 2026-07-23 fix's own writeup claimed both subprocess calls in this
    # file got a timeout ("neither ... had a timeout ... Fixed both"), but
    # the actual commit (2f9d850) only added timeout= to the claude -p call
    # below. This call — `git diff --staged`, which can hang on a held
    # index.lock or a slow external diff/textconv driver — was left with
    # none, so the "hung process hangs git commit indefinitely" bug the fix
    # claimed to close was still reachable through the call one line above
    # it. See docs/project_notes/bugs.md 2026-08-06.
    diff = subprocess.check_output(["git", "diff", "--staged"], text=True, timeout=20)
except subprocess.TimeoutExpired:
    print("git diff --staged timed out after 20s", file=sys.stderr)
    raise SystemExit(1)
if not diff.strip():
    print("Nothing staged. Run `git add` first.")
    raise SystemExit(1)

try:
    # --safe-mode disables CLAUDE.md/skills/plugins/hooks/MCP-server
    # auto-discovery while leaving OAuth auth intact (unlike --bare, which
    # forces ANTHROPIC_API_KEY/apiKeyHelper and refuses to read the OAuth
    # session this script actually authenticates with — see key_facts.md
    # "No ANTHROPIC_API_KEY"). Without it, this call inherits whatever
    # CLAUDE.md happens to sit in the caller's cwd — verified live: a bare
    # `claude -p` from this repo's root loads this project's own
    # "MANDATORY routing rules" for a one-line commit-message completion
    # that never calls a tool. See docs/project_notes/bugs.md 2026-08-10.
    raw = subprocess.check_output(
        ["claude", "-p", "--safe-mode", SYSTEM + "\n\n" + diff],
        text=True,
        timeout=20,
        stderr=subprocess.PIPE,
    ).strip()
except subprocess.TimeoutExpired:
    print("claude -p timed out after 20s", file=sys.stderr)
    raise SystemExit(1)
except subprocess.CalledProcessError as e:
    print(f"claude -p exited {e.returncode}: {(e.stderr or '').strip()[:200]}", file=sys.stderr)
    raise SystemExit(1)
except FileNotFoundError:
    print("claude CLI not found on PATH", file=sys.stderr)
    raise SystemExit(1)

# Safety filter — drop any line that looks like attribution
msg = "\n".join(
    l for l in raw.splitlines()
    if not _STRIP_RE.search(l)
).strip()

print(msg)
